acq = oscilloscope_single_acquisition:new():points(points):count(count):segmented(true)
trigger = oscilloscope_edge_trigger:new("EXT")
trigger:level(5, oscilloscope_quantity:new(2000.0, "mV")):slope(oscilloscope_trigger_slope.rising):mode(oscilloscope_trigger_mode.normal)
quant = oscilloscope_quantity:new(range, "ms")
rtb01 = rtx_instrument_configuration:new(quant, acq, trigger, timeout);
chan_1 = oscilloscope_channel:new(1)
chan_1:state(true):attenuation(oscilloscope_quantity:new(1, "V")):range(oscilloscope_quantity:new(26, "V")):label(oscilloscope_label:new("voltage", true))
chan_2 = oscilloscope_channel:new(2)
chan_2:state(true):attenuation(oscilloscope_quantity:new(10, "A")):range(oscilloscope_quantity:new(40, "V")):label(oscilloscope_label:new("current", true))
chan_3 = oscilloscope_channel:new(3)
chan_3:state(true):attenuation(oscilloscope_quantity:new(1, "V")):range(oscilloscope_quantity:new(7, "V")):label(oscilloscope_label:new("frame", true))
rtb01:channel(chan_1)
rtb01:channel(chan_2)
rtb01:channel(chan_3)
