#
# configure.ps1 [!output CURRENT_DATE]
#
# Copyright (C) 2007 by Visualisierungsinstitut der Universität Stuttgart.
# Alle Rechte vorbehalten.
# Copyright (C) 2007 by Christoph Müller. Alle Rechte vorbehalten.
#
#
# THIS FILE HAS BEEN GENERATED BY THE [!output WIZARD_DIALOG_TITLE] WIZARD!
#


# Ask for directories
$PathToVISLib = read-host "Specify path to VISlib [`"[!output VISLIB_DIR]`"]"
if ($PathToVISLib -eq "") {
    $PathToVISLib = "[!output VISLIB_DIR]"
}


# Create property sheet
$PropertySheet = "<?xml version=`"1.0`" encoding=`"Windows-1252`"?>
<VisualStudioPropertySheet
    ProjectType=`"Visual C++`"
    Version=`"8.00`"
    Name=`"VISlib Import Properties`"
    >
    <Tool
        Name=`"VCCLCompilerTool`"
        AdditionalIncludeDirectories=`"&quot;`$(VISlibDir)\base\include&quot;[!if VISLIB_CLUSTER]; &quot;`$(VISlibDir)\cluster\include&quot;[!endif][!if VISLIB_D3D]; &quot;`$(VISlibDir)\d3d\include&quot;[!endif][!if VISLIB_GL]; &quot;`$(VISlibDir)\gl\include&quot;[!endif][!if VISLIB_GRAPHICS]; &quot;`$(VISlibDir)\graphics\include&quot;[!endif][!if VISLIB_MATH]; &quot;`$(VISlibDir)\math\include&quot;[!endif][!if VISLIB_NET]; &quot;`$(VISlibDir)\net\include&quot;[!endif][!if VISLIB_SYS]; &quot;`$(VISlibDir)\sys\include&quot;[!endif]`"
    />
    <Tool
        Name=`"VCLinkerTool`"
        AdditionalDependencies=`"vislibbase`$(BitsD).lib[!if VISLIB_CLUSTER] vislibcluster`$(BitsD).lib[!endif][!if VISLIB_D3D] vislibd3d`$(BitsD).lib[!endif][!if VISLIB_GL] vislibgl`$(BitsD).lib[!endif][!if VISLIB_GRAPHICS] vislibgraphics`$(BitsD).lib[!endif][!if VISLIB_MATH] vislibmath`$(BitsD).lib[!endif][!if VISLIB_NET] vislibnet`$(BitsD).lib[!endif][!if VISLIB_SYS] vislibsys`$(BitsD).lib[!endif][!output ADDITIONAL_LIBRARIES]`"
        AdditionalLibraryDirectories=`"&quot;`$(VISlibDir)\lib&quot;`"
    />
    <UserMacro
        Name=`"VISlibDir`"
        Value=`"$PathToVISLib`"
    />
</VisualStudioPropertySheet>"


# Write property sheet
ni . -name [!output PROPS_FILENAME] -force -type "file" -value ($PropertySheet | out-string) >> $null
