#! /bin/sh
# configure.sh 12.4.2008
#
# Copyright (C) 2008 by Visualisierungsinstitut der Universität Stuttgart.
# Alle Rechte vorbehalten.
# Copyright (C) 2008 by Christoph Müller. Alle Rechte vorbehalten.
#
#
# THIS FILE HAS BEEN GENERATED BY THE Visual C++ 2005 Project with VISlib support WIZARD!
#


# Ask for directories
echo -n "Specify path to VISlib [\"../\"]: "
read PathToVISLib
if [ -z "${PathToVISLib}" ]; then
    PathToVISLib="../"
fi


# Create makefile include
Today=$(date +"%d.%m.%Y")
PropertySheet=$(cat << _EOF_
# ExtLibs.mk ${Today}
#
# THIS FILE HAS BEEN GENERATED BY configure.sh!
#

ifeq (\$(shell uname -p), x86_64)
    VISlibPlatform := Lin64
    VISlibBits := 64
else
    VISlibPlatform := Lin32
    VISlibBits = 32
endif

VISlibDir := ${PathToVISLib}

VISlibIncludeDirs := \$(VISlibDir)/base/include \$(VISlibDir)/cluster/include \$(VISlibDir)/gl/include \$(VISlibDir)/graphics/include \$(VISlibDir)/math/include \$(VISlibDir)/net/include \$(VISlibDir)/sys/include

VISlibLibDir := \$(VISlibDir)/lib

VISlibsRelease :=  vislibcluster\$(VISlibBits) vislibgl\$(VISlibBits) vislibgraphics\$(VISlibBits) vislibsys\$(VISlibBits) vislibnet\$(VISlibBits) vislibmath\$(VISlibBits) vislibbase\$(VISlibBits)

VISlibsDebug := \$(addsuffix d, \$(VISlibsRelease))

_EOF_
)


# Write makefile include
echo "${PropertySheet}" > ExtLibs.mk

exit 0
