# ExtLibs.mk 15.04.2008
#
# THIS FILE HAS BEEN GENERATED BY configure.sh!
#

ifeq ($(PLATFORM), x64)
    VISlibPlatform := Lin64
    VISlibBits := 64
else
    VISlibPlatform := Lin32
    VISlibBits = 32
endif

VISlibDir := ..

VISlibIncludeDirs := $(VISlibDir)/base/include $(VISlibDir)/cluster/include $(VISlibDir)/clustergl/include $(VISlibDir)/gl/include $(VISlibDir)/graphics/include $(VISlibDir)/math/include $(VISlibDir)/net/include $(VISlibDir)/sys/include

VISlibLibDir := $(VISlibDir)/lib

VISlibsRelease :=  vislibclustergl$(VISlibBits) vislibcluster$(VISlibBits) vislibgl$(VISlibBits) vislibgraphics$(VISlibBits) vislibnet$(VISlibBits) vislibsys$(VISlibBits) vislibmath$(VISlibBits) vislibbase$(VISlibBits)

VISlibsDebug := $(addsuffix d, $(VISlibsRelease))
