-- You probably want to set the instance you want to take a screenshot of.
-- Remember that for a lua project the instance name is the first parameter
-- of the mmCreate(View|Job) call!
-- -v ::imagemaker::imgmaker::view inst
-- also, set the output filename
-- -v ::imagemaker::imgmaker::filename screenshot.png
-- and the resolution
-- -v ::imagemaker::imgmaker::imgWidth 1280
-- -v ::imagemaker::imgmaker::imgHeight 720
mmCreateJob("imagemaker", "ScreenShooter", "imgmaker")
-- or set defaults here
-- mmSetParamValue("::imagemaker::imgmaker::imgWidth", "1920")
-- mmSetParamValue("::imagemaker::imgmaker::imgHeight", "1080")