mmCreateView("testgeospheres", "View3D", "::testview")
mmCreateModule("SimpleGeoSphereRenderer", "::rnd")
mmCreateModule("TestSpheresDataSource", "::dat")
mmCreateCall("CallRender3D", "::testview::rendering", "::rnd::rendering")
mmCreateCall("MultiParticleDataCall", "::rnd::getData", "::dat::getData")
