#
# Makefile  13.09.2006 (mueller)
#
# Copyright (C) 2006 by Universitaet Stuttgart (VIS). Alle Rechte vorbehalten.
#

-include ../common.mk

TargetName := vislibsys

IncludeDir += ../base/include ../math/include

ExcludeFromBuild += ./src/DynamicFunctionPointer.cpp ./src/PAMException.cpp ./src/ImpersonationContext.cpp

-include ../librules.mk