mmCreateView("GraphEntry_1","View3DGL","::View3DGL_1") 

mmCreateModule("OverrideParticleGlobals","::OverrideParticleGlobals_1") 
mmCreateModule("BoundingBoxRenderer","::BBox") 
mmCreateModule("MMPLDDataSource","::Data") 
mmCreateModule("SphereRenderer","::Renderer") 
mmCreateModule("ClipPlane","::ClipPlane_1") 
mmCreateModule("DistantLight","::DistantLight_1") 
mmCreateModule("TransferFunction","::TF") 

mmCreateCall("MultiParticleDataCall","::OverrideParticleGlobals_1::indata","::Data::getdata")
mmCreateCall("CallRender3DGL","::BBox::chainRendering","::Renderer::rendering")
mmCreateCall("MultiParticleDataCall","::Renderer::getdata","::OverrideParticleGlobals_1::outData")
mmCreateCall("CallGetTransferFunction","::Renderer::gettransferfunction","::TF::gettransferfunction")
mmCreateCall("CallLight","::Renderer::lights","::DistantLight_1::deployLightSlot")
mmCreateCall("CallClipPlane","::Renderer::getclipplane","::ClipPlane_1::getclipplane")
mmCreateCall("CallRender3DGL","::View3DGL_1::rendering","::BBox::rendering")

mmSetParamValue("::OverrideParticleGlobals_1::overrideAllLists",[=[true]=])
mmSetParamValue("::OverrideParticleGlobals_1::list",[=[0]=])
mmSetParamValue("::OverrideParticleGlobals_1::overrideRadius",[=[false]=])
mmSetParamValue("::OverrideParticleGlobals_1::radius",[=[0.500000]=])
mmSetParamValue("::OverrideParticleGlobals_1::overrideColor",[=[false]=])
mmSetParamValue("::OverrideParticleGlobals_1::color",[=[white]=])
mmSetParamValue("::OverrideParticleGlobals_1::overrideInt",[=[false]=])
mmSetParamValue("::OverrideParticleGlobals_1::minInt",[=[0.000000]=])
mmSetParamValue("::OverrideParticleGlobals_1::maxInt",[=[99999.000000]=])
mmSetParamValue("::BBox::enableBoundingBox",[=[true]=])
mmSetParamValue("::BBox::boundingBoxColor",[=[#ffffff]=])
mmSetParamValue("::BBox::smoothLines",[=[true]=])
mmSetParamValue("::BBox::enableViewCube",[=[false]=])
mmSetParamValue("::BBox::viewCubePosition",[=[top right]=])
mmSetParamValue("::BBox::viewCubeSize",[=[100]=])
mmSetParamValue("::Data::filename",[=[]=])
mmSetParamValue("::Data::limitMemory",[=[false]=])
mmSetParamValue("::Data::limitMemorySize",[=[2048]=])
mmSetParamValue("::Data::overrideLocalBBox",[=[false]=])
mmSetParamValue("::Renderer::scaling",[=[1.000000]=])
mmSetParamValue("::Renderer::forceTime",[=[false]=])
mmSetParamValue("::Renderer::useLocalBbox",[=[false]=])
mmSetParamValue("::Renderer::flag storage::selectedColor",[=[#ff0000]=])
mmSetParamValue("::Renderer::flag storage::softSelectedColor",[=[#ff8080]=])
mmSetParamValue("::Renderer::splat::alphaScaling",[=[5.000000]=])
mmSetParamValue("::Renderer::splat::attenuateSubpixel",[=[false]=])
mmSetParamValue("::Renderer::ssbo::staticData",[=[false]=])
mmSetParamValue("::Renderer::ambient occlusion::enableLighting",[=[false]=])
mmSetParamValue("::Renderer::ambient occlusion::useGsProxies",[=[false]=])
mmSetParamValue("::Renderer::ambient occlusion::volumeSize",[=[128]=])
mmSetParamValue("::Renderer::ambient occlusion::apex",[=[50.000000]=])
mmSetParamValue("::Renderer::ambient occlusion::offset",[=[0.010000]=])
mmSetParamValue("::Renderer::ambient occlusion::strength",[=[1.000000]=])
mmSetParamValue("::Renderer::ambient occlusion::coneLength",[=[0.800000]=])
mmSetParamValue("::Renderer::ambient occlusion::highPrecisionTexture",[=[false]=])
mmSetParamValue("::Renderer::outline::width",[=[2.000000]=])
mmSetParamValue("::Renderer::renderMode",[=[Simple]=])
mmSetParamValue("::ClipPlane_1::enable",[=[false]=])
mmSetParamValue("::ClipPlane_1::colour",[=[#808080]=])
mmSetParamValue("::ClipPlane_1::normal",[=[1;0;0]=])
mmSetParamValue("::ClipPlane_1::point",[=[0;0;0]=])
mmSetParamValue("::ClipPlane_1::dist",[=[0.000000]=])
mmSetParamValue("::DistantLight_1::Intensity",[=[1.000000]=])
mmSetParamValue("::DistantLight_1::Color",[=[#cccccc]=])
mmSetParamValue("::DistantLight_1::Direction",[=[-0.25;-0.5;-0.75]=])
mmSetParamValue("::DistantLight_1::AngularDiameter",[=[0.000000]=])
mmSetParamValue("::DistantLight_1::EyeDirection",[=[true]=])
mmSetParamValue("::TF::TransferFunction",[=[]=])
mmSetParamValue("::View3DGL_1::camstore::settings",[=[]=])
mmSetParamValue("::View3DGL_1::camstore::overrideSettings",[=[false]=])
mmSetParamValue("::View3DGL_1::camstore::autoSaveSettings",[=[false]=])
mmSetParamValue("::View3DGL_1::camstore::autoLoadSettings",[=[true]=])
mmSetParamValue("::View3DGL_1::resetViewOnBBoxChange",[=[false]=])
mmSetParamValue("::View3DGL_1::anim::play",[=[false]=])
mmSetParamValue("::View3DGL_1::anim::speed",[=[4.000000]=])
mmSetParamValue("::View3DGL_1::anim::time",[=[0.000000]=])
mmSetParamValue("::View3DGL_1::backCol",[=[#000020]=])
mmSetParamValue("::View3DGL_1::showLookAt",[=[false]=])
mmSetParamValue("::View3DGL_1::viewKey::MoveStep",[=[0.500000]=])
mmSetParamValue("::View3DGL_1::viewKey::RunFactor",[=[2.000000]=])
mmSetParamValue("::View3DGL_1::viewKey::AngleStep",[=[90.000000]=])
mmSetParamValue("::View3DGL_1::viewKey::FixToWorldUp",[=[true]=])
mmSetParamValue("::View3DGL_1::viewKey::MouseSensitivity",[=[3.000000]=])
mmSetParamValue("::View3DGL_1::viewKey::RotPoint",[=[Look-At]=])
mmSetParamValue("::View3DGL_1::hookOnChange",[=[false]=])
mmSetParamValue("::View3DGL_1::cam::position",[=[0;0;4.91631746]=])
mmSetParamValue("::View3DGL_1::cam::orientation",[=[0;-0;-0;1]=])
mmSetParamValue("::View3DGL_1::cam::projectiontype",[=[Perspective]=])
mmSetParamValue("::View3DGL_1::cam::convergenceplane",[=[0.000000]=])
mmSetParamValue("::View3DGL_1::cam::centeroffset",[=[0;0]=])
mmSetParamValue("::View3DGL_1::cam::halfaperturedegrees",[=[28.647890]=])
mmSetParamValue("::View3DGL_1::cam::halfdisparity",[=[0.025000]=])
mmSetParamValue("::View3DGL_1::cam::ovr::up",[=[0;0;0]=])
mmSetParamValue("::View3DGL_1::cam::ovr::lookat",[=[0;0;0]=])
mmSetParamValue("::View3DGL_1::view::defaultView",[=[Front]=])
mmSetParamValue("::View3DGL_1::view::defaultOrientation",[=[Top]=])
mmSetParamValue("::View3DGL_1::view::cubeOrientation",[=[0;0;0;1]=])
mmSetParamValue("::View3DGL_1::view::showViewCube",[=[false]=])

