#
# Makefile  13.09.2006 (mueller)
#
# Copyright (C) 2006 by Universitaet Stuttgart (VIS). Alle Rechte vorbehalten.
#

-include ../common.mk

TargetName := vislibmath

IncludeDir += ../base/include

ExcludeFromBuild += $(InputDir)/Cuboid.cpp $(InputDir)/Dimension.cpp $(InputDir)/Dimension2D.cpp $(InputDir)/Dimension3D.cpp $(InputDir)/Matrix4x4.cpp $(InputDir)/Quaternion.cpp $(InputDir)/Rectangle.cpp $(InputDir)/Plane.cpp

-include ../librules.mk