#! /bin/sh
# configure.sh [!output CURRENT_DATE]
#
# Copyright (C) 2008 by Visualisierungsinstitut der Universität Stuttgart.
# Alle Rechte vorbehalten.
# Copyright (C) 2008 by Christoph Müller. Alle Rechte vorbehalten.
#
#
# THIS FILE HAS BEEN GENERATED BY THE [!output WIZARD_DIALOG_TITLE] WIZARD!
#


# Ask for directories
echo -n "Specify path to VISlib [\"[!output LIN_VISLIB_DIR]\"]: "
read PathToVISLib
if [ -z "${PathToVISLib}" ]; then
    PathToVISLib="[!output LIN_VISLIB_DIR]"
fi


# Create makefile include
Today=$(date +"%d.%m.%Y")
PropertySheet=$(cat << _EOF_
# [!output LIN_PROPS_FILENAME] ${Today}
#
# THIS FILE HAS BEEN GENERATED BY configure.sh!
#

ifeq (\$(shell uname -p), x86_64)
    VISlibPlatform := Lin64
    VISlibBits := 64
else
    VISlibPlatform := Lin32
    VISlibBits = 32
endif

VISlibDir := ${PathToVISLib}

VISlibIncludeDirs := \$(VISlibDir)/base/include[!if VISLIB_CLUSTER] \$(VISlibDir)/cluster/include[!endif][!if VISLIB_GL] \$(VISlibDir)/gl/include[!endif][!if VISLIB_GRAPHICS] \$(VISlibDir)/graphics/include[!endif][!if VISLIB_MATH] \$(VISlibDir)/math/include[!endif][!if VISLIB_NET] \$(VISlibDir)/net/include[!endif][!if VISLIB_SYS] \$(VISlibDir)/sys/include[!endif]


VISlibLibDir := \$(VISlibDir)/lib

VISlibsRelease := [!if VISLIB_CLUSTER] vislibcluster\$(VISlibBits)[!endif][!if VISLIB_GL] vislibgl\$(VISlibBits)[!endif][!if VISLIB_GRAPHICS] vislibgraphics\$(VISlibBits)[!endif][!if VISLIB_NET] vislibnet\$(VISlibBits)[!endif][!if VISLIB_SYS] vislibsys\$(VISlibBits)[!endif][!if VISLIB_MATH] vislibmath\$(VISlibBits)[!endif] vislibbase\$(VISlibBits)

VISlibsDebug := \$(addsuffix d, \$(VISlibsRelease))

_EOF_
)


# Write makefile include
echo "${PropertySheet}" > [!output LIN_PROPS_FILENAME]

exit 0
