/*
 * vislibversion.h
 *
 * Copyright (C) 2008 by Universitaet Stuttgart (VIS). Alle Rechte vorbehalten.
 */

#ifndef VISLIB_VISLIBVERSION_H_INCLUDED
#define VISLIB_VISLIBVERSION_H_INCLUDED
#if (defined(_MSC_VER) && (_MSC_VER > 1000))
#pragma once
#endif /* (defined(_MSC_VER) && (_MSC_VER > 1000)) */
#if defined(_WIN32) && defined(_MANAGED)
#pragma managed(push, off)
#endif /* defined(_WIN32) && defined(_MANAGED) */

/*
 * This header contains defines holding the version number constants of the
 * vislib (all projects, excluding extension).
 *
 * THIS FILE IS GENERATED FROM THE FILE vislibversion.template.h
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

/**
 * Major version number of the vislib
 */
#define VISLIB_VERSION_MAJOR 0


/**
 * Minor version number of the vislib
 */
#define VISLIB_VERSION_MINOR 3


/**
 * Revision version number of the vislib
 */
#define VISLIB_VERSION_REVISION     $VISLIB_VERSION$


/**
 * Revision numbers of vislib subprojects
 */
#define VISLIB_BASE_REVISION        $VISLIB_BASE_REVISION$
#define VISLIB_CLUSTER_REVISION     $VISLIB_CLUSTER_REVISION$
#define VISLIB_CLUSTERD3D_REVISION  $VISLIB_CLUSTERD3D_REVISION$
#define VISLIB_CLUSTERGL_REVISION   $VISLIB_CLUSTERGL_REVISION$
#define VISLIB_D3D_REVISION         $VISLIB_D3D_REVISION$
#define VISLIB_GL_REVISION          $VISLIB_GL_REVISION$
#define VISLIB_GRAPHICS_REVISION    $VISLIB_GRAPHICS_REVISION$
#define VISLIB_MATH_REVISION        $VISLIB_MATH_REVISION$
#define VISLIB_NET_REVISION         $VISLIB_NET_REVISION$
#define VISLIB_SYS_REVISION         $VISLIB_SYS_REVISION$

#if $VISLIB_HAS_MODIFICATIONS$
#define VISLIB_DIRTY_BUILD 1
#endif


/**
 * Build version number of the vislib
 */
#if defined(DEBUG) || defined(_DEBUG)
#if defined(VISLIB_DIRTY_BUILD)
#define VISLIB_VERSION_BUILD 3
#else
#define VISLIB_VERSION_BUILD 1
#endif
#else /* defined(DEBUG) || defined(_DEBUG) */
#if defined(VISLIB_DIRTY_BUILD)
#define VISLIB_VERSION_BUILD 2
#else
#define VISLIB_VERSION_BUILD 0
#endif
#endif /* defined(DEBUG) || defined(_DEBUG) */


/*
 * VISLIB_STRINGIZING_HELPERS for macro argument expansion
 */
#ifndef VISLIB_STRINGIZING_HELPERS
#define VISLIB_STRINGIZING_HELPERS

#define VISLIB_STRINGIZING_HELPER_INTERNAL(arg) #arg
#define VISLIB_STRINGIZING_HELPER(arg) VISLIB_STRINGIZING_HELPER_INTERNAL(arg)
#define VISLIB_STRINGIZING_W_HELPER_INTERNAL(arg) L ## #arg
#define VISLIB_STRINGIZING_W_HELPER(arg) VISLIB_STRINGIZING_W_HELPER_INTERNAL(arg)

#endif /* VISLIB_STRINGIZING_HELPERS */


/**
 * The vislib version number ANSI string.
 * Implementation note: Add no spaces after new line!!!
 */
#define VISLIB_VERSION_STR VISLIB_STRINGIZING_HELPER(VISLIB_VERSION_MAJOR.\
VISLIB_VERSION_MINOR.VISLIB_VERSION_REVISION.VISLIB_VERSION_BUILD)


/**
 * The vislib version number ANSI string.
 */
#define VISLIB_VERSION_STRA VISLIB_VERSION_STR


/**
 * The vislib version number unicode string.
 * Implementation note: Add no spaces after new line!!!
 */
#define VISLIB_VERSION_STRW VISLIB_STRINGIZING_W_HELPER(VISLIB_VERSION_MAJOR.\
VISLIB_VERSION_MINOR.VISLIB_VERSION_REVISION.VISLIB_VERSION_BUILD)


#if defined(_WIN32) && defined(_MANAGED)
#pragma managed(pop)
#endif /* defined(_WIN32) && defined(_MANAGED) */
#endif /* VISLIB_VISLIBVERSION_H_INCLUDED */
