#!/usr/bin/perl
#
# build_include_table.pl
# VISlib 2
#
# Copyright (C) 2015 by Sebastian Grottel
# Alle Rechte vorbehalten. All rights reserved
#
use strict;
use File::Find;

my $inc_path = "../../include";
my $outFile = "include_table.pl";

open (my $out, ">$outFile") || die "Cannot write output file \"$outFile\"\n";

print $out qq<#
# $outFile
# Copyright (C) 2015 by Sebastian Grottel
# Alle Rechte vorbehalten. All rights reserved
#
# Generated File! Do not edit!
#
# Generated by "build_include_table.pl"
#

\$vislib_includes = { 
>;

sub add_include_file {
	return unless -f;
	my $dir = $File::Find::dir;
	$dir =~ s|$inc_path/||;
	print $out "    '$_' => '$dir',\n";
}

find(\&add_include_file, $inc_path);

print $out qq<};
>;

close ($out);
exit 0;
