macro(CHECK_MMDEP option doc default depends)
		set(${option}_AVAILABLE 1)
    foreach(d ${depends})
        string(REGEX REPLACE " +" ";" CMAKE_DEPENDENT_OPTION_DEP "${d}")
        if(${CMAKE_DEPENDENT_OPTION_DEP})
        else()
            set(${option}_AVAILABLE 0)
        endif()
    endforeach()
    if(${option}_AVAILABLE)
        option(${option} "${doc}" "${default}")
        set(${option} "${${option}}" CACHE BOOL "${doc}" FORCE)
    else()
        message(FATAL_ERROR "To enable ${option}, you need to also enable ${depends}")
    endif()
endmacro()