#
# Makefile  13.09.2006 (mueller)
#
# Copyright (C) 2006 by Universitaet Stuttgart (VIS). Alle Rechte vorbehalten.
#

#
# This is the default VISlib makefile. Do not change it. Any per project 
# configuration must be done in the separate file project.mk. project.mk must
# be located in the same directory as this makefile.
#
# At least the TargetName variable must be set in project.mk.
#


# Include project default configuration.
-include ../config.mk

# Include user settings and override.
-include project.mk

# Include common build rules.
-include ../librules.mk
