name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  plugin_check:
    name: Plugin-Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Run plugin check
        run: .ci/check_plugins.sh
  shader_check:
    name: Shader-Check
    runs-on: ubuntu-24.04
    steps:
      - name: Install glslang
        run: |
          sudo apt-get update
          sudo apt-get install -y glslang-tools
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Run shader check
        run: .ci/check_shaders.sh
