name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  plugin_check:
    name: Plugin-Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Run plugin check
        run: .ci/check_plugins.sh
  shader_check:
    name: Shader-Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Download glslang
        run: |
          mkdir bin
          wget "https://github.com/KhronosGroup/glslang/releases/download/main-tot/glslang-main-linux-Release.zip"
          unzip -j "glslang-main-linux-Release.zip" "bin/glslang" -d ./bin
          rm "glslang-main-linux-Release.zip"
          echo "./bin" >> $GITHUB_PATH
      - name: Run shader check
        run: .ci/check_shaders.sh
