name: Shader-Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shader_check:
    name: Shader-Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Download glslang
        run: |
          mkdir bin
          wget "https://github.com/KhronosGroup/glslang/releases/download/main-tot/glslang-main-linux-Release.zip"
          unzip -j "glslang-main-linux-Release.zip" "bin/glslangValidator" -d ./bin
          rm "glslang-main-linux-Release.zip"
          echo "./bin" >> $GITHUB_PATH
      - name: Run shader check
        run: .ci/check_shaders.sh
