name: Vcpkg Cache

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: >-
        cmake -S . -B ${{ github.workspace }}/build -G "Visual Studio 16 2019"
        -DMEGAMOL_STOP_AFTER_VCPKG=ON
        -DMEGAMOL_USE_CGAL=ON
        -DMEGAMOL_USE_OSPRAY=ON
      env:
        VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-cache.megamol.org/{triplet}-{name}-{sha},readwrite,Authorization: Token ${{ secrets.CACHING_SERVER_SECRET }}"
  linux:
    strategy:
      fail-fast: false
      matrix:
        config:
          - docker_image: megamol_ci_ubuntu
            cc: clang-14
            cxx: clang++-14
          - docker_image: megamol_ci_ubuntu
            cc: gcc-11
            cxx: g++-11
    name: Linux
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/unistuttgart-visus/${{ matrix.config.docker_image }}:master
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: >-
        cmake -S . -B ${{ github.workspace }}/build -G "Unix Makefiles"
        -DMEGAMOL_STOP_AFTER_VCPKG=ON
        -DMEGAMOL_USE_CGAL=ON
        -DMEGAMOL_USE_OSPRAY=ON
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
        VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-cache.megamol.org/{triplet}-{name}-{sha},readwrite,Authorization: Token ${{ secrets.CACHING_SERVER_SECRET }}"
